import {
  Fingerprint,
  Home,
  User,
  Settings,
  LogOut,
  LogIn,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  QrCode,
  Info,
  Building,
  Building2,
  UserPlus,
  LayoutDashboard,
  BarChart,
  Shield,
  Heart,
  Wallet,
  ArrowRight,
  Mail,
  Lock,
  MapPin,
  DollarSign,
  AlertCircle,
  Users,
  Phone,
  Send,
  CheckCircle,
  Trophy,
  TrendingUp,
  Calendar,
  XCircle,
  Tag,
  Save,
  Camera,
  UserCog,
  Globe,
  AlertTriangle,
  Link,
} from 'lucide-react';

export const Icons = {
  fingerprint: Fingerprint,
  home: Home,
  user: User,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  qrCode: QrCode,
  info: Info,
  building: Building,
  building2: Building2,
  userPlus: UserPlus,
  dashboard: LayoutDashboard,
  barChart: BarChart,
  shield: Shield,
  heart: Heart,
  wallet: Wallet,
  arrowRight: ArrowRight,
  mail: Mail,
  lock: Lock,
  mapPin: MapPin,
  dollarSign: DollarSign,
  alertCircle: AlertCircle,
  users: Users,
  phone: Phone,
  send: Send,
  checkCircle: CheckCircle,
  trophy: Trophy,
  trendingUp: TrendingUp,
  calendar: Calendar,
  xCircle: XCircle,
  tag: Tag,
  save: Save,
  camera: Camera,
  userCog: UserCog,
  globe: Globe,
  alertTriangle: AlertTriangle,
  link: Link,
} as const;

export type IconName = keyof typeof Icons; 