# Version Control workflow is currently disabled as we're using Replit for deployment
name: Version Control

on:
  # Temporarily disable all triggers
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  
  # Only run manually if needed
  workflow_dispatch:

jobs:
  version:
    # Mark as skipped/disabled
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Workflow Disabled
        run: echo "Workflow is disabled - using Replit for deployment"